import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Nav } from '@/app/components'
import { Footer } from '@/app/sections'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Phone Store',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-color1'>
        <header className='bg-black py-8 '>
          <Nav />
        </header>
        <main>
          {children}
        </main>
        <footer className='bg-black py-8'>
          <Footer />
        </footer>
      </body>
    </html>
  )
}
